// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkaWsedYTdXPI6UikKcm0tVkanOkxw0fY',
    appId: '1:219275827080:web:53595773d0a89ada060c3d',
    messagingSenderId: '219275827080',
    projectId: 'e-book-95162',
    authDomain: 'e-book-95162.firebaseapp.com',
    storageBucket: 'e-book-95162.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgHi2SdylF68yT98pHh1SwjswCrYogP8',
    appId: '1:219275827080:android:71985db41f8edb63060c3d',
    messagingSenderId: '219275827080',
    projectId: 'e-book-95162',
    storageBucket: 'e-book-95162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqqgN2p_RIX8LbhYbvo9OKtZt_WaL1hbQ',
    appId: '1:219275827080:ios:1ca5fa15a7c32178060c3d',
    messagingSenderId: '219275827080',
    projectId: 'e-book-95162',
    storageBucket: 'e-book-95162.firebasestorage.app',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqqgN2p_RIX8LbhYbvo9OKtZt_WaL1hbQ',
    appId: '1:219275827080:ios:1ca5fa15a7c32178060c3d',
    messagingSenderId: '219275827080',
    projectId: 'e-book-95162',
    storageBucket: 'e-book-95162.firebasestorage.app',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkaWsedYTdXPI6UikKcm0tVkanOkxw0fY',
    appId: '1:219275827080:web:f3196e6977ae928b060c3d',
    messagingSenderId: '219275827080',
    projectId: 'e-book-95162',
    authDomain: 'e-book-95162.firebaseapp.com',
    storageBucket: 'e-book-95162.firebasestorage.app',
  );

}